Introduction
There’s been a lot of buzz in the recent year around Ethereum cryptocurrency and not without cause. Smart contracts is a new exciting concept that Ethereum introduced. What is it? Ethereum is a distributed ledger (same as bitcoin) but this ledger may contain not only accounts and balances, but also computer programs. Programs are first class citizen on Ethereum blockchain and they are not only stored on it, but they provide functions that might be called (same as you may deposit or withdraw money on the ledger’s account) and store its state on the blockchain. For software developers it would be a good analogy that Ethereum Blockchain is a something similar to a VM. There is a virtual machine with instances of objects that are stored in its memory (smart contract). Instances contain not only code that might be executed but also its state. The main difference is that the everything is stored on distributed ledger instead of RAM. This metaphor is not perfect and simplifies things a bit, but it's a good starting point.

So smart contracts:

are instances of contracts deployed on blockchain
have functions that might be called from outside of blockchain or by other smart contracts
like regular distributed ledger accounts: may contain, receive and send Ethereum
Blockchain is run by the Ethereum network nodes. To interact with it you need to communicate with the Ethereum network node. Communication might be direct (with your own hosted node) or via a proxy (there are projects like Metamask or Infura that provides access to the existing Ethereum nodes).

Smart contract - written in solidity and deployed on public Ethereum blockchain
HTML web page that customer will use to make payment
Piece of code that will allow existing e-commerce store to communicate with smart contract to check payment status.
I named my pet project Petunia and you may find it on github. Below I described components that I created to achieve my goal.

Contract is deployed on blockchain (it’s done just once for each e-commerce store). _billingAddress is stored in smart contract.
When customer places an order, the store calls smart contract function startNewPayment with paymentId (payment id is generated by the store) and price that needs to be paid. This calls tells smart contract that there is a new payment expected with given id and price.
Customer calls (I will explain later how) pay function with payment id from store and with amount of Ethereum that needs to be paid. Smart contract checks if the id and amount of Ether sent matches. If yes it accepts the payment and changes the status.
E-commerce store checks the payment status (it calls getStatus function) if status is Paid then e-commerce store will send goods to customer.
Finally the e-commerce store calls complete function and Ethereum from given payment is transferred to the billing address. Now crypto money is on the store’s account.
There is also alternative path, when e.g. ordered product is not available then e-commerce store will call refund function and transfer money back to the account that was used by the customer. You will complete contract code in find it in solidity directory, but if you’re new to Ethereum don’t dive there yet (read the post first).

